theme: jekyll-theme-midnight
title: "Bem vindo à página da Quadrangular Q Garage Web Labs"
subtitle: "We hope you have a great 'navegation'" 
description: "Like us on facebook and bookmark the page for more updates, future"
